### ISSUE TITLE
[Bug] 框的颜色出现错误

### ISSUE THREAD

**Issue by SherkeyXD** [Agnes4m/nonebot_plugin_maimai#1]
<img width="230" alt="2f66e4ffea17a40fcd86004ed2ca057d" src="https://github.com/Agnes4m/maimai_plugin/assets/57581480/a0bef39e-d270-4948-b608-cc030f7b392b">

不应该是金框吗（

**Comment by Agnes4m** [comment]
源码是这样的，我已修复，虽然也不是什么大问题））
